version: 1.0.0  # 必须包含版本号

experiment:
  material: 
    name: "CFRP"
    young_s: 70e9
    poisson_ratio: 0.3
    density: 1600
    thickness: 1nm

acquisition:
  device: "Keysight_N9020B"
  sampling_rate: 6.25e6

processing:
  pre_filters:
    - type: "baseline_correction"
      window: 500
    - type: "bandpass_filter"
      low_cutoff: 20Hz
      high_cutoff: 20kHz
  imaging_method: "delay_and_sum"
